$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        1000:{
            items:2
        },
        1500:{
            items:3
        }
    }
})